version: "3"

services:

  mysqldb:
    container_name: dbcontainer
    image: mysql
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: spring_rest_db
      MYSQL_ROOT_PASSWORD: root
